# Generated by Django 4.0.3 on 2022-03-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Autor'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
